#!/bin/bash

set -e

PLIST="com.selesse.screenshotwatcher.plist"

main() {
    which fswatch > /dev/null || brew install fswatch

    cp watch-and-rename-screenshots "$HOME/bin"
    sed -i '' -e "s/@USER@/$(whoami)/" "$HOME/bin/watch-and-rename-screenshots"

    sudo cp "$PLIST" /Library/LaunchDaemons/
    sudo sed -i '' -e "s/@USER@/$(whoami)/" "/Library/LaunchDaemons/$PLIST"
    sudo launchctl load "/Library/LaunchDaemons/$PLIST"
}

main
