#!/bin/bash

set -e

PLIST="com.selesse.screenshotwatcher.plist"
DESTINATION_FOLDER="$HOME/Library/LaunchAgents/"

main() {
    which fswatch > /dev/null || brew install fswatch

    ln -s $(pwd)/watch-and-rename-screenshots "$HOME/bin"

    cp "$PLIST" "$DESTINATION_FOLDER"
    sed -i '' -e "s/@USER@/$(whoami)/" "$DESTINATION_FOLDER/$PLIST"
    launchctl load "$DESTINATION_FOLDER/$PLIST"
}

main
