#!/bin/bash

set -e

PLIST="com.selesse.screenshotwatcher.plist"

main() {
    which fswatch > /dev/null || brew install fswatch

    cp watch-and-rename-screenshots "$HOME/bin"
    sed -i '' -e "s/@USER@/$(whoami)/" "$HOME/bin/watch-and-rename-screenshots"

    cp "$PLIST" "$HOME/Library/LaunchAgents/"
    sed -i '' -e "s/@USER@/$(whoami)/" "$HOME/Library/LaunchAgents/$PLIST"
    launchctl load "$HOME/Library/LaunchAgents/$PLIST"
}

main
